// Client-side helpers + constants for the FindurAI Workspace feature.

import type {
  ClarificationAnswer,
  GraphData,
  PreviewStructure,
  RelationType,
  StackToolDto,
  TaskEvaluation,
  WorkspaceCollectionDto,
  WorkspaceInsights,
  WorkspaceItemDto,
  WorkspaceItemType,
  WorkspaceProjectDto,
} from "@/types/workspace";

export const ITEM_TYPE_META: Record<
  WorkspaceItemType,
  { label: string; plural: string; emoji: string }
> = {
  playbook: { label: "Playbook", plural: "Playbooks", emoji: "📘" },
  knowledge: { label: "AI Memory", plural: "AI Memory", emoji: "🧠" },
  workflow: { label: "Workflow", plural: "Workflows", emoji: "🔁" },
  prompt: { label: "Prompt", plural: "Prompts", emoji: "✨" },
  decision: { label: "Decision", plural: "Decisions", emoji: "⚖️" },
  code: { label: "Code", plural: "Code Snippets", emoji: "💻" },
  reference: { label: "Reference", plural: "References", emoji: "🔗" },
  research: { label: "Research", plural: "Research", emoji: "🔬" },
  template: { label: "Template", plural: "Templates", emoji: "📐" },
  idea: { label: "Idea", plural: "Ideas", emoji: "💡" },
  bookmark: { label: "Bookmark", plural: "Bookmarks", emoji: "🔖" },
  guide: { label: "Guide", plural: "Guides", emoji: "📖" },
  checklist: { label: "Checklist", plural: "Checklists", emoji: "✅" },
  quiz: { label: "Quiz", plural: "Quizzes", emoji: "❓" },
  ai_conversation: { label: "AI Conversation", plural: "AI Conversations", emoji: "💭" },
  roadmap: { label: "Roadmap", plural: "Roadmaps", emoji: "🗺️" },
};

export const RELATION_META: Record<RelationType, string> = {
  related_to: "Related To",
  uses: "Uses",
  created_from: "Created From",
  depends_on: "Depends On",
  inspired_by: "Inspired By",
  generated_by: "Generated By",
};

export interface DefaultTemplate {
  id: string;
  name: string;
  emoji: string;
  type: WorkspaceItemType;
  description: string;
  markdownContent: string;
}

export const DEFAULT_TEMPLATES: DefaultTemplate[] = [
  {
    id: "tpl-playbook",
    name: "Playbook",
    emoji: "📘",
    type: "playbook",
    description: "A reusable recipe for a problem you solved with AI.",
    markdownContent:
      "## Goal\n\n\n## Problem\n\n\n## AI Tools Used\n\n- \n\n## Prompts\n\n\n## Workflow\n\n- [ ] Step 1\n- [ ] Step 2\n\n## Code Snippets\n\n```\n\n```\n\n## Resources\n\n- \n\n## Final Result\n\n\n## Lessons Learned\n\n- \n",
  },
  {
    id: "tpl-prompt",
    name: "Prompt",
    emoji: "✨",
    type: "prompt",
    description: "Reusable prompt with variables and examples.",
    markdownContent:
      "## Purpose\n\n\n## Prompt\n\n```\n\n```\n\n## Variables\n\n- \n\n## Expected Output\n\n\n## Example Input\n\n\n## Example Output\n\n\n## Notes\n",
  },
  {
    id: "tpl-workflow",
    name: "Workflow",
    emoji: "🔁",
    type: "workflow",
    description: "Step-by-step reusable workflow.",
    markdownContent:
      "## Goal\n\n\n## Steps\n\n- [ ] Step 1\n- [ ] Step 2\n- [ ] Step 3\n\n## Tools Used\n\n- \n\n## Expected Result\n\n\n## Notes\n",
  },
  {
    id: "tpl-knowledge",
    name: "Knowledge",
    emoji: "🧠",
    type: "knowledge",
    description: "Capture reusable AI knowledge.",
    markdownContent: "## Summary\n\n\n## Details\n\n\n## Sources\n\n- \n",
  },
  {
    id: "tpl-research",
    name: "Research",
    emoji: "🔬",
    type: "research",
    description: "Research notes with findings and open questions.",
    markdownContent:
      "## Question\n\n\n## Findings\n\n- \n\n## Open Questions\n\n- \n\n## Sources\n\n- \n",
  },
  {
    id: "tpl-meeting",
    name: "Meeting",
    emoji: "🗓️",
    type: "knowledge",
    description: "Meeting notes with decisions and action items.",
    markdownContent:
      "## Attendees\n\n- \n\n## Notes\n\n\n## Decisions\n\n- \n\n## Action Items\n\n- [ ] \n",
  },
  {
    id: "tpl-idea",
    name: "Idea",
    emoji: "💡",
    type: "idea",
    description: "Capture an idea before it disappears.",
    markdownContent: "## The Idea\n\n\n## Why It Matters\n\n\n## Next Step\n\n- [ ] \n",
  },
  {
    id: "tpl-decision",
    name: "Decision",
    emoji: "⚖️",
    type: "decision",
    description: "Document a decision and its context.",
    markdownContent:
      "## Decision\n\n\n## Context\n\n\n## Options Considered\n\n- \n\n## Why This Option\n\n\n## Consequences\n\n- \n",
  },
];

async function request<T>(url: string, init?: RequestInit): Promise<T> {
  const res = await fetch(url, init);
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(data.error || "Request failed");
  }
  return data as T;
}

const json = (body: unknown): RequestInit => ({
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify(body),
});

const patch = (body: unknown): RequestInit => ({
  method: "PATCH",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify(body),
});

export const workspaceApi = {
  // Projects
  listProjects: (userId: string) =>
    request<{ projects: WorkspaceProjectDto[] }>(
      `/api/workspace/projects?userId=${encodeURIComponent(userId)}`
    ).then((d) => d.projects),
  createProject: (data: Partial<WorkspaceProjectDto> & { userId: string; name: string }) =>
    request<{ project: WorkspaceProjectDto }>("/api/workspace/projects", json(data)).then(
      (d) => d.project
    ),
  updateProject: (id: string, data: Partial<WorkspaceProjectDto> & { userId: string }) =>
    request<{ project: WorkspaceProjectDto }>(`/api/workspace/projects/${id}`, patch(data)).then(
      (d) => d.project
    ),
  deleteProject: (id: string, userId: string) =>
    request<{ success: boolean }>(
      `/api/workspace/projects/${id}?userId=${encodeURIComponent(userId)}`,
      { method: "DELETE" }
    ),
  setProjectDeadline: (id: string, userId: string, deadline: string | null) =>
    request<{ project: WorkspaceProjectDto }>(
      `/api/workspace/projects/${id}`,
      patch({ userId, deadline })
    ).then((d) => d.project),

  // Collections
  listCollections: (userId: string, filters: { projectId?: string } = {}) => {
    const params = new URLSearchParams({ userId });
    if (filters.projectId) params.set("projectId", filters.projectId);
    return request<{ collections: WorkspaceCollectionDto[] }>(
      `/api/workspace/collections?${params}`
    ).then((d) => d.collections);
  },
  createCollection: (data: Partial<WorkspaceCollectionDto> & { userId: string; name: string }) =>
    request<{ collection: WorkspaceCollectionDto }>("/api/workspace/collections", json(data)).then(
      (d) => d.collection
    ),
  updateCollection: (id: string, data: Partial<WorkspaceCollectionDto> & { userId: string }) =>
    request<{ collection: WorkspaceCollectionDto }>(
      `/api/workspace/collections/${id}`,
      patch(data)
    ).then((d) => d.collection),
  deleteCollection: (id: string, userId: string) =>
    request<{ success: boolean }>(
      `/api/workspace/collections/${id}?userId=${encodeURIComponent(userId)}`,
      { method: "DELETE" }
    ),
  duplicateCollection: (id: string, userId: string) =>
    request<{ collection: WorkspaceCollectionDto; duplicatedFolders: number; duplicatedItems: number }>(
      `/api/workspace/collections/${id}/duplicate`,
      json({ userId })
    ),

  // Items
  listItems: (
    userId: string,
    filters: Partial<
      Record<"type" | "projectId" | "collectionId" | "q" | "tag" | "limit", string>
    > & { favorite?: boolean; archived?: boolean } = {}
  ) => {
    const params = new URLSearchParams({ userId });
    for (const [k, v] of Object.entries(filters)) {
      if (v !== undefined && v !== "") params.set(k, String(v));
    }
    return request<{ items: WorkspaceItemDto[] }>(`/api/workspace/items?${params}`).then(
      (d) => d.items
    );
  },
  getItem: (id: string, userId: string) =>
    request<{ item: WorkspaceItemDto }>(
      `/api/workspace/items/${id}?userId=${encodeURIComponent(userId)}`
    ).then((d) => d.item),
  createItem: (data: Partial<WorkspaceItemDto> & { userId: string; title: string; type: string }) =>
    request<{ item: WorkspaceItemDto }>("/api/workspace/items", json(data)).then((d) => d.item),
  updateItem: (id: string, data: Partial<WorkspaceItemDto> & { userId: string }) =>
    request<{ item: WorkspaceItemDto }>(`/api/workspace/items/${id}`, patch(data)).then(
      (d) => d.item
    ),
  deleteItem: (id: string, userId: string) =>
    request<{ success: boolean }>(
      `/api/workspace/items/${id}?userId=${encodeURIComponent(userId)}`,
      { method: "DELETE" }
    ),

  // Graph
  getGraph: (userId: string) =>
    request<GraphData>(`/api/workspace/graph?userId=${encodeURIComponent(userId)}`),

  // Search
  search: (userId: string, q: string) =>
    request<{
      results: { id: string; title: string; emoji: string; kind: string; href: string }[];
    }>(
      `/api/workspace/search?userId=${encodeURIComponent(userId)}&q=${encodeURIComponent(q)}`
    ).then((d) => d.results),

  // AI Stack
  listStack: (userId: string) =>
    request<{ tools: StackToolDto[] }>(
      `/api/workspace/stack?userId=${encodeURIComponent(userId)}`
    ).then((d) => d.tools),
  addStackTool: (data: { userId: string; name: string; emoji?: string; color?: string }) =>
    request<{ tool: StackToolDto }>("/api/workspace/stack", json(data)).then((d) => d.tool),
  updateStackTool: (
    id: string,
    data: { userId: string; incrementUsage?: boolean; name?: string; emoji?: string }
  ) => request<{ tool: StackToolDto }>(`/api/workspace/stack/${id}`, patch(data)).then((d) => d.tool),
  removeStackTool: (id: string, userId: string) =>
    request<{ success: boolean }>(
      `/api/workspace/stack/${id}?userId=${encodeURIComponent(userId)}`,
      { method: "DELETE" }
    ),

  // Insights
  getInsights: (userId: string) =>
    request<WorkspaceInsights>(`/api/workspace/insights?userId=${encodeURIComponent(userId)}`),

  // Save-anything helpers
  extractUrl: (url: string) =>
    request<{
      url: string
      title: string
      description: string
      kind: string
      emoji: string
      tags: string[]
    }>(`/api/workspace/extract?url=${encodeURIComponent(url)}`),
  suggestMeta: (content: string) =>
    request<{
      meta: { title: string; description: string; tags: string[]; aiTool: string; category: string }
    }>("/api/workspace/ai", json({ action: "suggest_meta", content })).then((d) => d.meta),
  getRelated: (userId: string, itemId: string) =>
    request<{
      items: { id: string; title: string; emoji: string; type: string }[]
      tools: { id: string; name: string; category: string }[]
    }>(
      `/api/workspace/related?userId=${encodeURIComponent(userId)}&itemId=${encodeURIComponent(itemId)}`
    ),

  // AI
  ai: (body: Record<string, unknown>) => request<any>("/api/workspace/ai", json(body)),

  // AI Workspace Generator
  generateWorkspace: (
    userId: string,
    goal: string,
    extra: {
      category?: string
      complexity?: "small" | "medium" | "large"
      depthChoice?: "sample" | "detailed" | "complete"
      clarificationAnswers?: ClarificationAnswer[]
      confirmedStructure?: PreviewStructure
      generationRequirements?: string
    } = {}
  ) =>
    request<{
      project: WorkspaceProjectDto
      primaryIntent: string
      secondaryIntent: string
      folderCount: number
      itemCount: number
      scopeNote?: string | null
    }>("/api/workspace/generate", json({ userId, goal, ...extra })),

  // Intent classifier (v2/v4): decides workspace / direct_answer / ambiguous,
  // plus a Small/Medium/Large complexity estimate for workspace intents.
  classifyGoal: (goal: string, forceWorkspace = false) =>
    request<{
      intent: "workspace" | "direct_answer" | "ambiguous"
      category?: string
      complexity?: "small" | "medium" | "large"
      directAnswer?: string
      disambiguationQuestion?: { question: string; options: string[] }
      clarificationQuestions?: { question: string; options: string[] }[]
    }>("/api/workspace/classify", json({ goal, forceWorkspace })),

  // Preview-confirm flow: cheap structure-only pass before full generation
  previewWorkspace: (
    goal: string,
    extra: {
      category?: string
      complexity?: "small" | "medium" | "large"
      depthChoice?: "sample" | "detailed" | "complete"
      clarificationAnswers?: ClarificationAnswer[]
      correction?: string
      previousStructure?: PreviewStructure
      generationRequirements?: string
    } = {}
  ) => request<PreviewStructure>("/api/workspace/preview", json({ goal, ...extra })),

  // Per-folder "Regenerate this" correction loop
  regenerateFolder: (userId: string, projectId: string, folderId: string, reason?: string) =>
    request<{ items: WorkspaceItemDto[] }>(
      "/api/workspace/regenerate-folder",
      json({ userId, projectId, folderId, reason })
    ).then((d) => d.items),

  // On-demand fill-in for a stub item
  generateItem: (userId: string, itemId: string) =>
    request<{ item: WorkspaceItemDto }>("/api/workspace/generate-item", json({ userId, itemId })).then(
      (d) => d.item
    ),

  // AI Task Evaluation: reviews a user's explanation of what they did for a
  // task before it can be marked done.
  evaluateTask: (userId: string, taskText: string, explanation: string, context?: string) =>
    request<TaskEvaluation>("/api/workspace/evaluate-task", json({ userId, taskText, explanation, context })),

  // Repairs a project generated before checklists were guaranteed for every
  // file — cheap no-op once nothing is left to fix.
  backfillMissions: (userId: string, projectId: string) =>
    request<{ scanned: number; updated: number }>(
      "/api/workspace/backfill-missions",
      json({ userId, projectId })
    ),
};

// Example playbooks offered on first run so nobody starts from a blank page
// (MVP plan, Phase 5). Created only when the user clicks — never auto-inserted.
export const EXAMPLE_PLAYBOOKS = [
  {
    title: "Example: Exam Preparation with AI",
    emoji: "🎓",
    tags: ["study", "example"],
    description: "How a student turns any syllabus into a 2-week AI study plan.",
    typeData: {
      goal: "Prepare for an exam in 2 weeks using AI",
      problem: "Too much material, no structure, and past papers going unused.",
      toolsUsed: ["ChatGPT", "Claude", "NotebookLM"],
      steps: [
        { id: "ex1-1", text: "Paste the syllabus and ask for a 14-day study plan", done: false, indent: 0 },
        { id: "ex1-2", text: "Generate summaries for each topic and save them here", done: false, indent: 0 },
        { id: "ex1-3", text: "Create practice questions from past papers", done: false, indent: 0 },
        { id: "ex1-4", text: "Daily: explain yesterday's weakest topic back to the AI", done: false, indent: 0 },
      ],
    },
    markdownContent:
      "## Prompt that does the heavy lifting\n\n```\nYou are my exam coach. Here is my syllabus: {{syllabus}}.\nBuild a 14-day plan with daily 2-hour blocks, weighting topics by mark distribution.\n```\n\n## Lessons Learned\n\n- Asking the AI to quiz you beats re-reading summaries.\n",
  },
  {
    title: "Example: Build a Portfolio Website",
    emoji: "💼",
    tags: ["webdev", "example"],
    description: "A developer ships a portfolio in a weekend with AI pair-programming.",
    typeData: {
      goal: "Ship a personal portfolio site in one weekend",
      problem: "Endless tweaking and no design skills.",
      toolsUsed: ["Cursor", "Claude", "v0"],
      steps: [
        { id: "ex2-1", text: "Generate 3 layout options and pick one", done: false, indent: 0 },
        { id: "ex2-2", text: "Scaffold with Next.js + Tailwind in Cursor", done: false, indent: 0 },
        { id: "ex2-3", text: "Write project descriptions with AI, edit by hand", done: false, indent: 0 },
        { id: "ex2-4", text: "Deploy and run Lighthouse fixes", done: false, indent: 0 },
      ],
    },
    markdownContent:
      "## Key prompt\n\n```\nAct as a senior frontend dev. Review my portfolio hero section for clarity\nand suggest 3 sharper headline options based on my resume: {{resume}}\n```\n",
  },
  {
    title: "Example: Startup Pitch Deck",
    emoji: "🚀",
    tags: ["startup", "example"],
    description: "A founder drafts, stress-tests and polishes a pitch with AI.",
    typeData: {
      goal: "Create a 10-slide investor pitch",
      problem: "The story is clear in your head but weak on slides.",
      toolsUsed: ["Claude", "Gamma", "ChatGPT"],
      steps: [
        { id: "ex3-1", text: "Draft the narrative arc (problem → wedge → why now)", done: false, indent: 0 },
        { id: "ex3-2", text: "Have the AI play a skeptical VC and attack the deck", done: false, indent: 0 },
        { id: "ex3-3", text: "Generate slide visuals in Gamma", done: false, indent: 0 },
        { id: "ex3-4", text: "Tighten every slide to one message", done: false, indent: 0 },
      ],
    },
    markdownContent:
      "## Stress-test prompt\n\n```\nYou are a skeptical seed investor. Here is my pitch: {{pitch}}.\nAsk me the 5 hardest questions, then rate each of my answers.\n```\n",
  },
] as const

// Human labels for activity feed entries derived from item timestamps
export function activityLabel(item: WorkspaceItemDto): string {
  const created = new Date(item.createdAt).getTime();
  const updated = new Date(item.updatedAt).getTime();
  const isNew = updated - created < 60 * 1000;
  const noun = ITEM_TYPE_META[item.type]?.label || "item";
  if (item.type === "playbook" && item.typeData?.solved) return `Solved with Playbook`;
  return isNew ? `Created ${noun}` : `Updated ${noun}`;
}

// Task-level progress rollup (workspace-generation-spec.md: "No manual
// progress editing" — progress is always derived, never set directly). A
// file with a generated checklist contributes its own done/total task count;
// a file with no checklist contributes as a single binary task.
export function taskUnits(item: WorkspaceItemDto): { done: number; total: number } {
  const steps = item.typeData?.steps;
  if (Array.isArray(steps) && steps.length > 0) {
    return { done: steps.filter((s) => s.done).length, total: steps.length };
  }
  return { done: item.completionStatus === "completed" ? 1 : 0, total: 1 };
}

export function parseMinutes(text: string | undefined): number {
  if (!text) return 0;
  const match = text.match(/(\d+(?:\.\d+)?)\s*(hour|hr|minute|min)/i);
  if (!match) return 0;
  const value = parseFloat(match[1]);
  return match[2].toLowerCase().startsWith("h") ? value * 60 : value;
}

export function formatMinutes(min: number): string {
  if (min <= 0) return "0 Minutes";
  const hours = min / 60;
  if (hours >= 1) {
    const rounded = Math.round(hours * 10) / 10;
    return `${rounded} Hour${rounded === 1 ? "" : "s"}`;
  }
  const rounded = Math.round(min);
  return `${rounded} Minute${rounded === 1 ? "" : "s"}`;
}

export function timeAgo(dateString: string): string {
  const seconds = Math.floor((Date.now() - new Date(dateString).getTime()) / 1000);
  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;
  return new Date(dateString).toLocaleDateString();
}
