// Defensive coercion + validation of AI JSON into our typed shapes.
//
// Nothing generated by the model reaches the browser without passing through
// here. The policy is: repair what is safely repairable (trim, clamp, drop a
// malformed item), and throw a controlled error when what's left is not worth
// showing — never render raw model output, and never send a half-formed shape
// to the UI.

import {
  MAX_FLASHCARDS,
  MAX_NOTE_SECTIONS,
  MAX_QUESTIONS,
  MAX_QUIZ_QUESTIONS,
} from "./config";
import type {
  Flashcard,
  FlashcardsResult,
  ItemDifficulty,
  NoteDefinition,
  NoteSection,
  NotesResult,
  QuestionKind,
  QuestionsResult,
  QuizQuestion,
  QuizResult,
  StudyQuestion,
} from "./types";

export class EmptyGenerationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmptyGenerationError";
  }
}

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

function str(v: unknown, max = 1000): string {
  return typeof v === "string" ? v.trim().slice(0, max) : "";
}

function strArray(v: unknown, maxItems: number, itemMax = 600): string[] {
  if (!Array.isArray(v)) return [];
  return v
    .filter((x): x is string => typeof x === "string" && x.trim().length > 0)
    .map((x) => x.trim().slice(0, itemMax))
    .slice(0, maxItems);
}

// Page references are only kept when they're plausible for this document —
// a model-invented page 400 in a 12-page PDF is dropped rather than displayed.
function pageArray(v: unknown, pageCount: number, allowPages: boolean): number[] {
  if (!allowPages || !Array.isArray(v)) return [];
  const pages = v
    .map((x) => (typeof x === "number" ? x : Number(x)))
    .filter((n) => Number.isInteger(n) && n >= 1 && n <= pageCount);
  return Array.from(new Set(pages)).sort((a, b) => a - b).slice(0, 12);
}

function difficulty(v: unknown, fallback: ItemDifficulty): ItemDifficulty {
  const s = typeof v === "string" ? v.trim().toLowerCase() : "";
  return s === "easy" || s === "medium" || s === "hard" ? s : fallback;
}

const QUESTION_KINDS: QuestionKind[] = ["recall", "conceptual", "application", "comparison", "explanation"];

function questionKind(v: unknown): QuestionKind {
  const s = typeof v === "string" ? v.trim().toLowerCase() : "";
  return (QUESTION_KINDS as string[]).includes(s) ? (s as QuestionKind) : "conceptual";
}

function makeId(prefix: string, index: number): string {
  return `${prefix}-${index}-${Math.random().toString(36).slice(2, 8)}`;
}

// ---------------------------------------------------------------------------
// Duplicate detection
// ---------------------------------------------------------------------------

// Strips the wording that makes "What is X?" and "Define X." look different,
// so near-duplicate cards collapse to the same key.
const STOP_WORDS = new Set([
  "what", "is", "are", "the", "a", "an", "of", "define", "definition", "describe",
  "explain", "how", "does", "do", "in", "to", "for", "and", "or", "which", "list",
  "name", "state", "give", "tell", "me", "about", "please", "briefly",
]);

function dedupeKey(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w && !STOP_WORDS.has(w))
    .sort()
    .join(" ");
}

function dedupeBy<T>(items: T[], key: (item: T) => string): T[] {
  const seen = new Set<string>();
  const out: T[] = [];
  for (const item of items) {
    const k = key(item);
    // An item whose key reduces to nothing carries no comparable content —
    // keep it rather than collapsing every such item into one.
    if (k && seen.has(k)) continue;
    if (k) seen.add(k);
    out.push(item);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Notes
// ---------------------------------------------------------------------------

interface SanitizeCtx {
  fallbackTitle: string;
  pageCount: number;
  allowPages: boolean;
  defaultDifficulty: ItemDifficulty;
}

function sanitizeDefinitions(v: unknown, max = 12): NoteDefinition[] {
  if (!Array.isArray(v)) return [];
  return v
    .map((d) => {
      const o = (d ?? {}) as Record<string, unknown>;
      return { term: str(o.term, 120), definition: str(o.definition, 600) };
    })
    .filter((d) => d.term && d.definition)
    .slice(0, max);
}

export function sanitizeNotes(raw: unknown, ctx: SanitizeCtx): NotesResult {
  const o = (raw ?? {}) as Record<string, unknown>;

  const sections: NoteSection[] = (Array.isArray(o.sections) ? o.sections : [])
    .map((s): NoteSection => {
      const sec = (s ?? {}) as Record<string, unknown>;
      return {
        title: str(sec.title, 160),
        summary: str(sec.summary, 1200),
        keyPoints: strArray(sec.keyPoints, 15, 500),
        definitions: sanitizeDefinitions(sec.definitions),
        examples: strArray(sec.examples, 8, 600),
        formulas: strArray(sec.formulas, 8, 300),
        sourcePages: pageArray(sec.sourcePages, ctx.pageCount, ctx.allowPages),
      };
    })
    // A section with a title but no content of any kind is noise, not notes.
    .filter(
      (s) =>
        s.title &&
        (s.summary || s.keyPoints.length > 0 || s.definitions.length > 0 || s.examples.length > 0)
    )
    .slice(0, MAX_NOTE_SECTIONS);

  const result: NotesResult = {
    type: "notes",
    title: str(o.title, 160) || ctx.fallbackTitle,
    overview: str(o.overview, 1500),
    sections,
    keyTakeaways: strArray(o.keyTakeaways, 10, 400),
  };

  if (result.sections.length === 0 && !result.overview) {
    throw new EmptyGenerationError("The AI returned no usable notes for this document.");
  }
  return result;
}

// ---------------------------------------------------------------------------
// Flashcards
// ---------------------------------------------------------------------------

export function sanitizeFlashcards(raw: unknown, ctx: SanitizeCtx, quantity: number): FlashcardsResult {
  const o = (raw ?? {}) as Record<string, unknown>;
  const rawCards = Array.isArray(o.cards) ? o.cards : Array.isArray(o.flashcards) ? o.flashcards : [];

  const cards: Flashcard[] = dedupeBy(
    rawCards
      .map((c) => {
        const card = (c ?? {}) as Record<string, unknown>;
        return {
          question: str(card.question, 400),
          answer: str(card.answer, 1200),
          topic: str(card.topic, 120),
          sourcePages: pageArray(card.sourcePages, ctx.pageCount, ctx.allowPages),
        };
      })
      .filter((c) => c.question && c.answer),
    (c) => dedupeKey(c.question)
  )
    .slice(0, Math.min(quantity, MAX_FLASHCARDS))
    .map((c, i) => ({ ...c, id: makeId("card", i) }));

  if (cards.length === 0) {
    throw new EmptyGenerationError("The AI returned no usable flashcards for this document.");
  }

  return { type: "flashcards", title: str(o.title, 160) || ctx.fallbackTitle, cards };
}

// ---------------------------------------------------------------------------
// Questions & Answers
// ---------------------------------------------------------------------------

export function sanitizeQuestions(raw: unknown, ctx: SanitizeCtx, quantity: number): QuestionsResult {
  const o = (raw ?? {}) as Record<string, unknown>;
  const rawQuestions = Array.isArray(o.questions) ? o.questions : [];

  const questions: StudyQuestion[] = dedupeBy(
    rawQuestions
      .map((q) => {
        const item = (q ?? {}) as Record<string, unknown>;
        return {
          question: str(item.question, 500),
          answer: str(item.answer, 2000),
          difficulty: difficulty(item.difficulty, ctx.defaultDifficulty),
          kind: questionKind(item.kind),
          topic: str(item.topic, 120),
          sourcePages: pageArray(item.sourcePages, ctx.pageCount, ctx.allowPages),
        };
      })
      .filter((q) => q.question && q.answer),
    (q) => dedupeKey(q.question)
  )
    .slice(0, Math.min(quantity, MAX_QUESTIONS))
    .map((q, i) => ({ ...q, id: makeId("q", i) }));

  if (questions.length === 0) {
    throw new EmptyGenerationError("The AI returned no usable questions for this document.");
  }

  return { type: "questions", title: str(o.title, 160) || ctx.fallbackTitle, questions };
}

// ---------------------------------------------------------------------------
// Quiz
// ---------------------------------------------------------------------------

export function sanitizeQuiz(raw: unknown, ctx: SanitizeCtx, quantity: number): QuizResult {
  const o = (raw ?? {}) as Record<string, unknown>;
  const rawQuestions = Array.isArray(o.questions) ? o.questions : [];

  const questions: QuizQuestion[] = dedupeBy(
    rawQuestions
      .map((q) => {
        const item = (q ?? {}) as Record<string, unknown>;
        const options = strArray(item.options, 6, 300);
        const correctRaw = typeof item.correctAnswer === "number" ? item.correctAnswer : Number(item.correctAnswer);

        return {
          question: str(item.question, 500),
          options,
          correctAnswer: Number.isInteger(correctRaw) ? correctRaw : -1,
          explanation: str(item.explanation, 1000),
          difficulty: difficulty(item.difficulty, ctx.defaultDifficulty),
          topic: str(item.topic, 120),
          sourcePages: pageArray(item.sourcePages, ctx.pageCount, ctx.allowPages),
        };
      })
      // An out-of-range correctAnswer isn't repairable — picking an index for
      // the model would mean grading the user against a made-up answer, so the
      // question is dropped instead.
      .filter(
        (q) =>
          q.question &&
          q.options.length >= 2 &&
          q.correctAnswer >= 0 &&
          q.correctAnswer < q.options.length &&
          // Duplicate options make the "one clearly correct answer" contract
          // meaningless, so drop those questions too.
          new Set(q.options.map((opt) => opt.toLowerCase())).size === q.options.length
      ),
    (q) => dedupeKey(q.question)
  )
    .slice(0, Math.min(quantity, MAX_QUIZ_QUESTIONS))
    .map((q, i) => ({ ...q, id: makeId("quiz", i) }));

  if (questions.length === 0) {
    throw new EmptyGenerationError("The AI returned no usable quiz questions for this document.");
  }

  return { type: "quiz", title: str(o.title, 160) || ctx.fallbackTitle, questions };
}

// ---------------------------------------------------------------------------
// Digest (intermediate stage for long documents)
// ---------------------------------------------------------------------------

export interface DigestTopic {
  title: string;
  summary: string;
  facts: string[];
  definitions: NoteDefinition[];
  formulas: string[];
  examples: string[];
  sourcePages: number[];
}

export function sanitizeDigest(raw: unknown, pageCount: number, allowPages: boolean): DigestTopic[] {
  const o = (raw ?? {}) as Record<string, unknown>;
  const topics = Array.isArray(o.topics) ? o.topics : [];
  return topics
    .map((t): DigestTopic => {
      const topic = (t ?? {}) as Record<string, unknown>;
      return {
        title: str(topic.title, 160),
        summary: str(topic.summary, 1200),
        facts: strArray(topic.facts, 25, 500),
        definitions: sanitizeDefinitions(topic.definitions, 15),
        formulas: strArray(topic.formulas, 10, 300),
        examples: strArray(topic.examples, 8, 500),
        sourcePages: pageArray(topic.sourcePages, pageCount, allowPages),
      };
    })
    .filter((t) => t.title && (t.summary || t.facts.length > 0))
    .slice(0, 40);
}

// Renders digested topics back into text for the final generation call, keeping
// page attribution attached so the generated items can still cite pages.
export function formatDigest(topics: DigestTopic[]): string {
  return topics
    .map((t) => {
      const lines = [`## ${t.title}`];
      // Same marker style the raw-text path uses, so the page-attribution rule
      // in the prompt reads identically whichever path produced the source.
      if (t.sourcePages.length) lines.push(`[PAGE ${t.sourcePages.join(", ")}]`);
      if (t.summary) lines.push(t.summary);
      if (t.facts.length) lines.push(...t.facts.map((f) => `- ${f}`));
      if (t.definitions.length) lines.push(...t.definitions.map((d) => `- ${d.term}: ${d.definition}`));
      if (t.formulas.length) lines.push(...t.formulas.map((f) => `- formula: ${f}`));
      if (t.examples.length) lines.push(...t.examples.map((e) => `- example: ${e}`));
      return lines.join("\n");
    })
    .join("\n\n");
}
